name: eecs498
channels:
  - defaults
dependencies:
  - python=3
  - jupyterlab=3
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - cudatoolkit=10.2
  - pytorch=1.9.0
  - matplotlib=3.3.4
  - imageio=2.9.0
  - scipy=1.6.2
  - pytorch-model-summary=0.1.1
  - ipywidgets=7.6.3
